### ISSUE TITLE
Using the Nuget package, INgrokHostedService is not available

### ISSUE THREAD

**Issue by WizX20** [kg73/NgrokAspNetCore#24]
For one, you should mention the nuget package on the main readme page.

When I install the package, I am unable to acces the _Ngrok.AspNetCore_ namespace. The only namespace available to me is _NgrokAspNetCore_.

In the sample you directly reference the _Ngrok.AspNetCore_ project, so yes, that will work.

**Comment by kbot7** [comment]
Thanks for the catch - I can take a look this weekend. I'm also open to accepting PRs if there's further changes you think would be helpful. 

To clarify, are you currently able to workaround this issue, or is it a total blocker for you?

**Comment by WizX20** [comment]
It's not a total blocker. I can fetch this repo, compil it and reference the binaries.

But, the NuGet package is not usable for me right now.

**Comment by kbot7** [comment]
I've just pushed the latest dev build to this repo's GitHub packages. Feel free to try it out.
https://github.com/kg73/NgrokAspNetCore/packages/199602

The current latest version on NuGet.org is 1.0.6. There was a namespace change from NgrokAspNetCore to Ngrok.AspNetCore between the 1.0.6 version and the latest in the develop branch. The latest build pushed to the GitHub NuGet uses the new namespace, which matches the README. 

The README is still out of date, and might not line up. The sample is the best source-of-truth at the moment. At minimum, you just need to add `services.AddNgrok()` in your ConfigureServices method on startup. I'm working on updating the README, and will post back here once done. In the meantime, if you try the latest dev package, let me know if you have further issues with it.

**Comment by kbot7** [comment]
Hi @WizX20, 

I've pushed out the first pre-release build to Nuget.org with your issue fixed. It is available here:
https://www.nuget.org/packages/Ngrok.AspNetCore/2.0.0-alpha1

I've also updated the readme with accurate setup and configuration information, as well as links to the nuget feeds on the top (thanks for the suggestion 😄). 

Please let me know if this solves your issue.

**Comment by WizX20** [comment]
Works like a charm.

**Some additional tips for anyone finding this**
Use it optionally in your _ConfigureServices_ (startup) method:
```
// Only use Ngrok on development environments
if (this.CurrentEnvironment.IsDevelopment())
{
  services.AddNgrok(options =>
  {
    // Add a ngrok yaml configuration file to configure a correct host header
    options.NgrokConfigProfile = $"{Directory.GetCurrentDirectory()}/Resources/Ngrok/ngrok.yml";
  });
}
```

Then use it somehwere in your code:
```
using System;
using Microsoft.Extensions.DependencyInjection;
using Ngrok.AspNetCore;

...

public MyConstructor(IServiceProvider serviceProvider)
{
  this.NgrokHostedService = serviceProvider.GetService<INgrokHostedService>();
}

private async Task MyMethod()
{
  var nGrokTunnel = await this.NgrokHostedService?.GetTunnelsAsync();
  var nGrokTunnelUrl = nGrokTunnel
    ?.Result
    ?.FirstOrDefault(t => t.Name.Equals("my-http-or-https-instance", StringComparison.OrdinalIgnoreCase))
    ?.PublicURL;

  if (!string.IsNullOrEmpty(nGrokTunnelUrl))
  {
    // DO STUFF
  }
}
```

**Example ngrok.yml**
```
tunnels:
    my-web-api:
        addr: 5000
        proto: http
        bind_tls: true
        host_header: localhost:5000
```
