### ISSUE TITLE
authtoken not needed

### ISSUE THREAD

**Issue by lastlink** [kg73/NgrokAspNetCore#34]
* is the authtoken not needed w/ this?, else where do we configure this?

**Comment by kbot7** [comment]
If your ngrok authtoken is saved in the default ngrok configuration file location, the ngrok process will use it when launched by this extension. 

Documentation on ngrok configuration can be found here: https://ngrok.com/docs#config

For example, if I am on Windows, the default Ngrok configuration path is `C:\Users\example\.ngrok2\ngrok.yml`. If my ngrok authtoken is saved in this file, the ngrok process launched by this project will use that authtoken, with no other configuration needed.

Does this help?

**Comment by lastlink** [comment]
Can we customize, set our own auth token via this service or does support need to be added? I see `NgrokConfigProfile` is not currently in use
